apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: litmus
  labels:
    purpose: testing
spec:
  containers:
    - name: test-container
      image: localhost:5000/jonsy13/e2e:ci
      env:
        - name: CYPRESS_BASE_URL
          value: "http://litmusportal-frontend-service:9091"
        - name: CYPRESS_INCLUDE_TAGS
          value: "login"
