---
## This worflow will build the litmus-e2e image for every new commit.
name: Air-gapped Support
on:
  workflow_dispatch:

jobs:
  air-gapped-job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      # Pulling kind/node image
      - run: |
          mkdir assets
          cp ./litmus/utils.sh runtime-assets/
          cp ./litmus/kind.sh runtime-assets/
          docker pull litmuschaos/litmusportal-frontend:ci && docker save litmuschaos/litmusportal-frontend:ci -o runtime-assets/litmusportal-frontend.tar
          docker pull litmuschaos/litmusportal-server:ci && docker save litmuschaos/litmusportal-server:ci -o runtime-assets/litmusportal-server.tar
          docker pull litmuschaos/litmusportal-auth-server:ci && docker save litmuschaos/litmusportal-auth-server:ci -o runtime-assets/litmusportal-auth-server.tar
          curl https://raw.githubusercontent.com/litmuschaos/litmus/master/litmus-portal/cluster-k8s-manifest.yml --output runtime-assets/litmus-portal-setup.yml

      # Creating a cluster with network none & mounting all assets inside the container as a host.
      - run: |
          docker run -t --rm --network none -v "$(pwd)"/runtime-assets:/air-gapped-kind/runtime-assets --privileged jonsy13/air-gapped-kind:ci /bin/bash -c "cd runtime-assets && ls && chmod +x ./kind.sh && ./kind.sh"
