---
## This worflow will build the litmus-e2e image for every new commit.
name: Air-gapped Support
on:
  workflow_dispatch:

jobs:
  air-gapped-job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Installing plugins
        run: |
          cd Cypress && npm i
          
      # Pulling kind/node image
      - name: Setting up Image Assets
        run: |
          mkdir runtime-assets
          cp ./litmus/utils.sh runtime-assets/
          cp ./litmus/kind.sh runtime-assets/
          docker pull -q litmuschaos/curl:latest && docker save litmuschaos/curl:latest -o runtime-assets/curl.tar
          docker pull -q litmuschaos/litmusportal-frontend:ci && docker save litmuschaos/litmusportal-frontend:ci -o runtime-assets/frontend.tar
          docker pull -q litmuschaos/litmusportal-server:ci && docker save litmuschaos/litmusportal-server:ci -o runtime-assets/gql-server.tar
          docker pull -q litmuschaos/litmusportal-auth-server:ci && docker save litmuschaos/litmusportal-auth-server:ci -o runtime-assets/auth-server.tar
          docker pull -q litmuschaos/mongo:4.2.8 && docker save litmuschaos/mongo:4.2.8 -o runtime-assets/mongo.tar
          docker pull -q cypress/included:7.3.0 && docker save cypress/included:7.3.0 -o runtime-assets/cypress.tar
          curl https://raw.githubusercontent.com/litmuschaos/litmus/master/litmus-portal/cluster-k8s-manifest.yml --output runtime-assets/litmus-portal-setup.yml

      # Creating a cluster with network none & mounting all assets inside the container as a host.
      - name: Creating an Air-gapped KIND Cluster & Running Tests
        run: |
          docker run -t --rm --network none \
          -v "$(pwd)"/runtime-assets:/air-gapped-kind/runtime-assets \
          -v "$(pwd)"/Cypress:/air-gapped-kind/Cypress \
          --privileged jonsy13/air-gapped-kind:ci /bin/bash \
          -c "cd runtime-assets && ls && chmod +x ./kind.sh && ./kind.sh"
