---
name: Image Tar ball exporter
on:
  workflow_dispatch:
    inputs:
      image_name_with_tag:
        default: ""

jobs:
  images-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setting up Image Assets
        run: |
          source ./litmus/utils.sh
          mkdir assets
          chaos_center_tar_maker

      - name: Archive Assets
        uses: actions/upload-artifact@v2
        with:
          name: assets
          path: assets
