---
name: Push
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: build/Dockerfile.litmusctl
          platforms: linux/amd64,windows/386,windows/amd64
          tags: jonsy13/litmusctl:ci